name: Build
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.REPOSITORY_NAME }}/gaming-grid-creator:${{ github.sha }},${{ secrets.REPOSITORY_NAME }}/gaming-grid-creator:latest,
